### ISSUE TITLE
Fontin vaihto webbisivulle

### ISSUE THREAD

**Issue by vranki** [pikaviestin/website-www.pikaviestin.fi#7]
Nykyinen fonti on aika ruma IMO. En kuitenkaan keksinyt miten tuossa meidän jekyll+teemahimmelissä asetetaan oletusfontti.

Ehdotettuja fontteja: Lato, Poppins, Muli, Open Sans.

**Comment by SyntaxErrol** [comment]
Multa vois irrota tähän PR. Saitilla näyttää nykyään olevan käytössä 3 fonttia, Merriweather (otsikot), Georgia (leipä) ja Menlo (koodi), joista ensimmäiset kaksi serifejä ja jälkimmäinen monospace sans-serifi. Ensimmäinen näistä ladataan Googlen fonteista ja loppujen oletetaan löytyvän käyttäjän laitteelta.

Ehdotusten perusteella se rumuus pesii ilmeisesti noissa pääteviivallisissa serif-fonteissa. Tuo Georgia ainakin on hyvin laajalti käytetty, joten sen vaihto voisi freesata sivua. Myös se, että otsikot olisi serifiä ja leipäteksti sans-serifiä, tai toisin päin, voi olla mukava yhdistelmä.

Suosittaisin joko
- https://fonts.google.com/specimen/Mulish
- https://fonts.google.com/specimen/Open+Sans tai nykyisen otsikkofontin pääteviivatonta versiota
- https://fonts.google.com/specimen/Merriweather+Sans

jotka ovat saatavilla [variable fontteina](https://en.wikipedia.org/wiki/Variable_font), jotka ovat moderneja ja käteviä esim. portaattoman paksuussäädön kannalta ja sen, että tätä varten ei tarvita useita fonttitiedostoja. Tällä on toki vähemmän merkitystä silloin, kun käytetään Googlen hostausta, mutta siitäkin pitäisi GDPR:n vuoksi siirtyä pois ja hostamaan fontit paikallisesti. Tällöin pienempi tiedostomäärä muotoilumahdollisuuksista tinkimättä olisi kevyemmin ylläpidettävä ratkaisu.

Pohdinpä tätä vähän ja koitan tuottaa vaikka jonkin demon.
