### ISSUE TITLE
Siltausohjeet päivitettävä

### ISSUE THREAD

**Issue by vranki** [pikaviestin/website-www.pikaviestin.fi#8]
Kapsin siltausohjeet https://www.kapsi.fi/palvelut/matrix.html ovat vanhentuneet ja vähän huonot muutenkin. 

Vaihtoehdot:
 - Joku jolla on voimaa, korjaa ne kapsi.fi-sivuille jolloin niistä on myös riemua kapsilaisille
 - Copypastetaan ohjeet pikaviestin.fi-sivulle ja parannetaan.

Ensimmäinen olisi parempi vaihtoehto.

**Comment by vranki** [comment]
Sivun sisältö uudistettu ja toimitettu Uumakselle Kapsille laitettavaksi.

**Comment by samip5** [comment]
Tämä on tehty.
